import { DataTypes } from 'sequelize';
import { unsignedInteger } from './types.js';

/**
 * Somewhere outside that wants to be told when something happens here.
 *
 * The events are stored as a JSON array of keys rather than a join table: the
 * list is short, always read whole, and never queried across endpoints. A
 * subscription with no events is deliberately legal and deliberately silent —
 * it is what an endpoint looks like while somebody is setting it up.
 *
 * `secret` signs the payload so the receiver can prove the call came from here
 * and was not altered on the way. It is generated by us, not supplied, because
 * a secret a user types is a secret a user reuses. It is returned exactly once,
 * at creation, and never read back through the API afterwards.
 *
 * `isActive` is not the same as deleted. An endpoint whose receiver is down
 * gets switched off so the queue stops piling up against it, and switched back
 * on when the far end returns — its delivery history intact, which is the only
 * way to answer what was missed.
 */
export default (sequelize) => sequelize.define('WebhookEndpoint', {
  id: { type: unsignedInteger(sequelize), autoIncrement: true, primaryKey: true },

  label: { type: DataTypes.STRING(120), allowNull: false },
  url: { type: DataTypes.STRING(500), allowNull: false },

  // Shared secret for the HMAC signature. Write-mostly: set here, read by the
  // dispatcher, never returned to a client after creation.
  secret: { type: DataTypes.STRING(128), allowNull: false },

  // Which events this endpoint wants, e.g. ["stock.moved","invoice.created"].
  events: { type: DataTypes.TEXT, allowNull: false, defaultValue: '[]' },

  isActive: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true },

  // Health, kept here so the list screen does not have to aggregate deliveries
  // to answer "is this one working". Reset on a success.
  consecutiveFailures: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
  lastSuccessAt: { type: DataTypes.DATE, allowNull: true },
  lastFailureAt: { type: DataTypes.DATE, allowNull: true },
  lastFailureReason: { type: DataTypes.STRING(500), allowNull: true },

  authadd: { type: DataTypes.INTEGER, allowNull: true },
  authlstedit: { type: DataTypes.INTEGER, allowNull: true },
  authdel: { type: DataTypes.INTEGER, allowNull: true },
  detstatus: { type: DataTypes.BOOLEAN, defaultValue: false },
  delondt: { type: DataTypes.DATE, allowNull: true },
}, {
  timestamps: true,
  createdAt: 'addondt',
  updatedAt: 'editondt',
  tableName: 'webhook_endpoints',
  indexes: [
    // The dispatcher's only question: who is listening right now.
    { fields: ['is_active', 'detstatus'] },
  ],
});
