import { Router } from 'express';
import authRoutes from './auth.routes.js';
import categoryRoutes from './category.routes.js';
import customerRoutes from './customer.routes.js';
import productRoutes from './product.routes.js';
import invoiceRoutes from './invoice.routes.js';
import salesOrderRoutes from './salesOrder.routes.js';
import quotationRoutes from './quotation.routes.js';
import deliveryChallanRoutes from './deliveryChallan.routes.js';
import salesReturnRoutes from './salesReturn.routes.js';
import inventoryRoutes from './inventory.routes.js';
import masterDataRoutes from './masterData.routes.js';
import reportRoutes from './report.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import settingsRoutes from './settings.routes.js';
import supplierRoutes from './supplier.routes.js';
import userRoutes from './user.routes.js';
import invoiceTemplateRoutes from './invoiceTemplate.routes.js';
import { authenticate } from '../middleware/authMiddleware.js';

const router = Router();
router.use('/auth', authRoutes);
router.use('/categories', authenticate, categoryRoutes);
router.use('/customers', authenticate, customerRoutes);
router.use('/products', authenticate, productRoutes);
router.use('/suppliers', authenticate, supplierRoutes);
router.use('/invoices', authenticate, invoiceRoutes);
router.use('/sales-orders', authenticate, salesOrderRoutes);
router.use('/quotations', authenticate, quotationRoutes);
router.use('/delivery-challans', authenticate, deliveryChallanRoutes);
router.use('/sales-returns', authenticate, salesReturnRoutes);
router.use('/inventory', authenticate, inventoryRoutes);
router.use('/master-data', authenticate, masterDataRoutes);
router.use('/reports', authenticate, reportRoutes);
router.use('/dashboard', authenticate, dashboardRoutes);
router.use('/settings', authenticate, settingsRoutes);
router.use('/invoice-templates', authenticate, invoiceTemplateRoutes);
router.use('/users', authenticate, userRoutes);

export default router;
