import { Op, fn, col } from 'sequelize';
import { WarehouseBin } from '../models/index.js';
import { BIN_LEVELS, BIN_LEVEL_DEPTH } from '../models/warehouseBin.model.js';

/**
 * The shape of the building, and the order somebody walks it.
 *
 * A bin tree says what contains what. It does not say what is *next to* what,
 * and those are different questions: the last rack of aisle 1 and the last rack
 * of aisle 2 are adjacent in the building but sit in different branches of the
 * tree. Picking by tree order therefore sends a picker up and down every aisle
 * in turn; picking by sequence walks them once.
 *
 * So `pickSequence` is the authority on routing and the tree is the authority
 * on containment, and neither is derived from the other. The sequence can be
 * assigned by hand — a supervisor who knows the building beats any algorithm —
 * or generated by the serpentine walk below as a sane starting point.
 */

/** Bins that can actually hold stock. Only leaves are pickable places. */
export const STORAGE_LEVEL = 'Bin';

/** Ancestors of a bin, outermost first — the "Zone A › Aisle 1 › Rack 2" trail. */
export async function pathTo(binId, transaction) {
  const trail = [];
  let current = await WarehouseBin.findByPk(binId, { transaction });
  let guard = 0;

  // Guarded against a cycle. A parent chain that loops would hang the request,
  // and a mis-set parentId is a data error, not an impossibility.
  while (current && guard < BIN_LEVELS.length + 2) {
    trail.unshift(current);
    if (!current.parentId) break;
    current = await WarehouseBin.findByPk(current.parentId, { transaction });
    guard += 1;
  }
  return trail;
}

/** "ZONE-A › AISLE-01 › RACK-01 › BIN-001" */
export async function pathLabel(binId, transaction) {
  return (await pathTo(binId, transaction)).map((b) => b.code).join(' › ');
}

/**
 * Refuses a parent that would make an impossible building.
 *
 * A rack inside a shelf, or a zone inside a bin, is not a harmless oddity: the
 * whole point of the hierarchy is that walking it produces a sensible route, and
 * an inverted rung produces a route through a shelf into an aisle.
 */
export async function assertValidNesting({ level, parentId, branchId }, transaction) {
  if (!parentId) return;

  const parent = await WarehouseBin.findOne({
    where: { id: parentId, detstatus: false },
    transaction,
  });
  if (!parent) {
    throw Object.assign(new Error('Parent location not found'), { status: 404 });
  }
  if (Number(parent.branchId) !== Number(branchId)) {
    throw Object.assign(
      new Error('A location cannot sit inside a different warehouse'),
      { status: 400 },
    );
  }
  if (BIN_LEVEL_DEPTH[level] <= BIN_LEVEL_DEPTH[parent.level]) {
    throw Object.assign(
      new Error(`A ${level} cannot sit inside a ${parent.level} — the hierarchy runs ${BIN_LEVELS.join(' → ')}`),
      { status: 400 },
    );
  }
}

/**
 * Every storage bin at a location, in the order a picker walks past them.
 *
 * Unsequenced bins sort last, not first. A bin nobody has placed in the route
 * is one nobody has thought about, and putting it at the head of the list would
 * start every pick round at an unknown corner of the building.
 */
export async function walkOrder(branchId, { includeInactive = false } = {}) {
  const where = { branchId, detstatus: false, level: STORAGE_LEVEL };
  if (!includeInactive) where.isActive = true;

  const bins = await WarehouseBin.findAll({ where });

  return bins.sort((a, b) => {
    const aSeq = a.pickSequence;
    const bSeq = b.pickSequence;
    if (aSeq === null && bSeq === null) return String(a.code).localeCompare(String(b.code));
    if (aSeq === null) return 1;
    if (bSeq === null) return -1;
    if (aSeq !== bSeq) return aSeq - bSeq;
    return String(a.code).localeCompare(String(b.code));
  });
}

/** Where a bin falls in the walk. Used to order a pick list by route. */
export async function sequenceMap(branchId) {
  const bins = await WarehouseBin.findAll({
    where: { branchId, detstatus: false },
    attributes: ['id', 'pickSequence', 'code'],
  });
  return new Map(bins.map((b) => [b.id, {
    pickSequence: b.pickSequence, code: b.code,
  }]));
}

/**
 * Generates a walking route and writes it onto the bins.
 *
 * The default is a serpentine walk: down the first aisle, back up the second,
 * down the third. It is what a picker does naturally, and it beats aisle-order
 * numbering — which sends them back to the top of every aisle before starting
 * the next one, walking the length of the building once per aisle.
 *
 * Numbering leaves gaps (100, 110, 120…) so a bin added later can be slotted
 * into the route without renumbering the whole warehouse, which would otherwise
 * invalidate every printed pick list in the building.
 *
 * Nothing is guessed about a warehouse whose layout is unknown: with no
 * coordinates the bins are ordered by their codes, which is what a naming
 * convention like A-01-03 already encodes.
 */
export async function generateWalkRoute(branchId, {
  serpentine = true, start = 100, step = 10, userId = null, dryRun = false,
} = {}) {
  const bins = await WarehouseBin.findAll({
    where: { branchId, detstatus: false, level: STORAGE_LEVEL, isActive: true },
  });

  if (!bins.length) return { assigned: 0, route: [] };

  // Group by aisle so the serpentine can reverse alternate ones. Which ancestor
  // is "the aisle" is decided per bin, since not every warehouse defines one.
  const grouped = new Map();
  for (const bin of bins) {
    const trail = await pathTo(bin.id);
    const aisle = trail.find((b) => b.level === 'Aisle')
      || trail.find((b) => b.level === 'Zone');
    const key = aisle ? `${aisle.level}:${aisle.code}` : 'ungrouped';
    if (!grouped.has(key)) grouped.set(key, { aisle, bins: [] });
    grouped.get(key).bins.push(bin);
  }

  const withinAisle = (list) => list.sort((a, b) => {
    // Along the aisle if we know where things are, by code if we do not.
    const ax = a.positionX;
    const bx = b.positionX;
    if (ax !== null && bx !== null && Number(ax) !== Number(bx)) return Number(ax) - Number(bx);
    return String(a.code).localeCompare(String(b.code), undefined, { numeric: true });
  });

  const aisles = [...grouped.entries()].sort((a, b) => a[0].localeCompare(b[0], undefined, { numeric: true }));

  const route = [];
  let sequence = start;
  aisles.forEach(([, group], index) => {
    const ordered = withinAisle(group.bins);
    // Every other aisle is walked in reverse, so the picker ends each aisle at
    // the mouth of the next one instead of returning to where they started.
    const walk = serpentine && index % 2 === 1 ? [...ordered].reverse() : ordered;
    for (const bin of walk) {
      route.push({ binId: bin.id, code: bin.code, pickSequence: sequence, aisle: group.aisle?.code || null });
      sequence += step;
    }
  });

  if (!dryRun) {
    for (const stop of route) {
      await WarehouseBin.update(
        { pickSequence: stop.pickSequence, authlstedit: userId },
        { where: { id: stop.binId } },
      );
    }
  }

  return { assigned: route.length, serpentine, start, step, dryRun, route };
}

/**
 * Sequences a caller has supplied by hand.
 *
 * Duplicates are allowed — two bins facing each other across an aisle are
 * genuinely the same stop on the walk — but they are reported back so a
 * supervisor can see it was deliberate rather than a typo.
 */
export async function applySequences(branchId, entries = [], userId = null) {
  const ids = entries.map((e) => Number(e.binId));
  const bins = await WarehouseBin.findAll({
    where: { id: { [Op.in]: ids }, branchId, detstatus: false },
  });
  const known = new Map(bins.map((b) => [b.id, b]));

  const applied = [];
  const rejected = [];

  for (const entry of entries) {
    const bin = known.get(Number(entry.binId));
    if (!bin) {
      rejected.push({ binId: entry.binId, reason: 'Not a bin at this warehouse' });
      continue;
    }
    const seq = entry.pickSequence === null ? null : Number(entry.pickSequence);
    if (seq !== null && !Number.isInteger(seq)) {
      rejected.push({ binId: entry.binId, reason: 'Pick sequence must be a whole number' });
      continue;
    }
    await bin.update({ pickSequence: seq, authlstedit: userId });
    applied.push({ binId: bin.id, code: bin.code, pickSequence: seq });
  }

  const counts = await WarehouseBin.findAll({
    where: { branchId, detstatus: false, pickSequence: { [Op.ne]: null } },
    attributes: ['pickSequence', [fn('COUNT', col('id')), 'n']],
    group: ['pick_sequence'],
    having: sequelizeHavingMoreThanOne(),
    raw: true,
  }).catch(() => []);

  return {
    applied,
    rejected,
    sharedStops: (counts || []).map((r) => ({ pickSequence: Number(r.pickSequence), bins: Number(r.n) })),
  };
}

/** `HAVING COUNT(id) > 1`, kept out of the query body for readability. */
function sequelizeHavingMoreThanOne() {
  return WarehouseBin.sequelize.literal('COUNT(id) > 1');
}

/** Gaps and unsequenced bins — what a supervisor fixes before printing routes. */
export async function routeHealth(branchId) {
  const bins = await WarehouseBin.findAll({
    where: { branchId, detstatus: false, level: STORAGE_LEVEL, isActive: true },
    attributes: ['id', 'code', 'pickSequence'],
  });

  const unsequenced = bins.filter((b) => b.pickSequence === null);
  const sequenced = bins.filter((b) => b.pickSequence !== null);

  const bySeq = new Map();
  for (const bin of sequenced) {
    const key = bin.pickSequence;
    if (!bySeq.has(key)) bySeq.set(key, []);
    bySeq.get(key).push(bin.code);
  }

  return {
    branchId,
    totalBins: bins.length,
    sequenced: sequenced.length,
    unsequenced: unsequenced.map((b) => ({ binId: b.id, code: b.code })),
    duplicateStops: [...bySeq.entries()]
      .filter(([, codes]) => codes.length > 1)
      .map(([pickSequence, codes]) => ({ pickSequence, codes })),
    // A route is usable once every active bin has a place in it.
    ready: unsequenced.length === 0 && bins.length > 0,
  };
}
